spring.application.name=Banco Celeste

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_celeste
spring.datasource.username=postgres
spring.datasource.password=kenko1800

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

